nombre: Build SegurApp APK

en:
  empujar:
    ramas: [ principal ]
  flujo_de_trabajo:

empleos:
  construir:
    runs-on: ubuntu-latest

    pasos:
      - nombre: Descargar código
        Usos: acciones/checkout@v4

      - nombre: Instalar Node.js
        usos: actions/setup-node@v4
        con:
          versión del nodo: '20'

      - nombre: Instalar Java 17
        Usos: actions/setup-java@v4
        con:
          versión de Java: '17'
          distribución: 'temurin'

      - nombre: Preparar carpeta www
        correr: |
          mkdir -p www
          cp index.html app.js sw.js manifest.json www/
          cp -r iconos www/
          node get-libs.js
          cp -r lib www/

      - nombre: Instalar condensador
        ejecutar: npm install

      - nombre: Inicializar Capacitor
        ejecutar: npx cap init "SegurApp" "com.salvadormg.segurapp" --web-dir www

      - nombre: AÃ±adir Android
        ejecutar: npx cap agregar android

      - nombre: Sincronizar
        ejecutar: sincronización de capacidad npx android

      - nombre: Crear archivos nativos de Java
        correr: |
          DIR="android/app/src/main/java/com/salvadormg/segurapp"
          mkdir -p $DIR
          eco"" | base64 -d > $DIR/NativeStoragePlugin.java
          eco "=" | base64 -d > $DIR/Actividad Principal.java
          echo "âœ… Archivos Java creados"
          head -3 $DIR/NativeStoragePlugin.java
          cabeza -3 $DIR/MainActivity.java

      - nombre: Permisos AndroidManifest
        correr: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i 's|</manifest>| <uses-permission android:name="android.permission.CAMERA" />\n <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />\n <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />\n <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />\n <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />\n <uses-permission android:name="android.permission.VIBRATE" />\n</manifest>|' $MANIFEST

      - nombre: Permisos Gradle
        ejecutar: chmod +x android/gradlew

      - nombre: Construir APK
        correr: |
          CD Android
          ./gradlew assembleDebug --no-daemon

      - nombre: Subir APK
        Usos: acciones/cargar-artefacto@v4
        con:
          nombre: SegurApp-v2.0
          Ruta: android/app/build/outputs/apk/debug/app-debug.apk
          días de retención: 30
